Horse Rents:
    rent1:
        name: 'Sally'
        speed: 5
        price: 500
        type: 'Horse'
        color: 'creamy'
        time: 3
        armor: 'iron'
        isOwnable: false     
    rent2:
        name: 'Bobby'
        speed: 3
        price: 1000
        type: 'Horse'
        color: 'creamy'
        time: 10
        armor: 'iron'
        isOwnable: false

#This will store all instances of horses in the world
Database Settings:
   usemysql: false
   host: 'localhost'
   port: 3306
   databaseName: classicModels
   user: root
   pass: root
        
        
#Notes: the time value is in minutes 
#isOwnable determinies whether or not the horse is buyable
       