Horse Rents:
      rent1:
        name: 'Sally'
        speed: 5
        price: 500
        type: 'Horse'
        color: 'creamy'
        time: 3
        armor: 'iron'
        isOwnable: false     
      rent2:
        name: 'Bobby'
        speed: 3
        price: 1000
        type: 'Horse'
        color: 'creamy'
        time: 10
        armor: 'iron'
        isOwnable: false
        
        
#Notes: the time value is in minutes 
#isOwnable determinies whether or not the horse is buyable
       